name: cinemapedia_dos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.0
  go_router: ^11.0.0
  riverpod_annotation: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
